source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/gligorkot/MyPods.git'

use_frameworks!

workspace 'GKStorageKitExample'

target :'GKStorageKitExample' do
    project 'GKStorageKitExample.xcodeproj'
    platform :ios, '9.0'

    pod 'GKStorageKit', :path => '../'

     target :'GKStorageKitTests' do
         pod 'Nimble', '~> 8.x'
         pod 'SwiftTestUtils', '~> 0.0.1'
     end
end
