name: CI

on: pull_request

jobs:
  pod-lint:
    name: Pod lint
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Bundle install
      run: bundle install
      
    - name: Set up XCode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Pod lint
      run: bundle exec pod lib lint --verbose --fail-fast --swift-version=5.5
      shell: bash

  test-no-iOS-host-13:
    name: Run swift tests that don't require iOS host on MacOS 13
    runs-on: macos-13
    strategy:
      matrix:
        # all available versions of XCode14
        xcodeVersions: ['14.1', '14.2', '14.3']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up XCode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcodeVersions }}

    - name: Run tests that don't require iOS host
      run: swift test -c debug -Xswiftc -enable-testing
      shell: bash

  test-keychain-iOS-host-13-XCode14:
    name: Run swift tests that require keychain entitlement on XCode 14
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up XCode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Run tests that require iOS host for keychain entitlement
      run: xcodebuild -project SecureStorageTestsHostApp/SecureStorageTestsHostApp.xcodeproj -scheme SecureStorageTestsHostApp -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" test
      shell: bash