name: Run tests

on: push

jobs:
  test-10_15:
    runs-on: macos-10.15
    strategy:
      matrix:
        # latest 11 and all available versions 12
        xcodeVersions: ['11.7', '12.0', '12.1', '12.2', '12.3', '12.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up XCode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcodeVersions }}

    - name: Run tests
      run: swift test -c debug -Xswiftc -enable-testing
      shell: bash

  test-11:
    runs-on: macos-11
    strategy:
      matrix:
        # latest 12 and all available versions 13
        xcodeVersions: ['12.5', '13.0', '13.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up XCode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcodeVersions }}

    - name: Run tests
      run: swift test -c debug -Xswiftc -enable-testing
      shell: bash